config/routes.rb
Brproject::Application.routes.draw do

  get '/project' => 'home#project'
  get '/organisations' => 'home#organisations'
  get '/developers' => 'home#developers'
  get '/contact' => 'home#contact'
  resources :home

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def project

  end

  def organisations

  end

  def developers

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<br/>
<h4>Wanna get in touch?</h4>
<p>That is nice to hear :). We are IceFlag and these are our details:</p>

<address>
  <strong>IceFlag</strong><br>
  Delweg 32<br>
  6902PJ, Zevenaar<br>
  <abbr title="Phone">P:</abbr> (0031) 6 395 767 48
</address>

<address>
  <strong>Dirk Grandjean</strong><br>
  <a href="mailto:#">dirkgrandjean@live.nl</a>
</address>

<p>When the project gets initiated, IceFlag will launch its website (iceflag.com) and the blue robin project will have its own e-mail address.</p>

app/views/home/developers.html.erb
<br/>
<h5>Let's have a look under the hood..</h5>
<p>We all know that the real beautity of any software is the code itself. Blue Robin has been written in Ruby on Rails (famous from yellowpage, twitter and github). Ruby on Rails (RoR) is a framework which allows rails developers to contribute to any project since it has been written in a framework and therefore the folder structure is very similar to any other rails project.</p>

<h5>How to join?</h5>
<p>The code will be published on Github including a wiki page. On github any developer can join, download and deploy new versions. If you would like to know more about github, please go <%= link_to 'here', 'https://github.com/', :target => "_blank" %>. Their slogan is: "Build better software together", nuff said.</p>

<h5>Ruby gems - Templates</h5>
<p>The software is making use of gems which are libraries developed by the RoR community. To give an example, all the exporting excel templates are build on this gem: <%= link_to 'Randym Axls', 'https://github.com/randym/axlsx', :target => "_blank" %></p>
<p>His blog can be found <%= link_to 'here', 'http://axlsx.blog.randym.net/', :target => "_blank" %> while <%= link_to 'here', 'https://github.com/randym/axlsx/blob/master/examples/example.rb', :target => "_blank" %> code examples can be found. The power of RoR is its many libraries (gems) which are sustained pretty well. If you are an IT expert in the organisation you can change the template according your own needs with help of the well-maintained documentation.</p>

app/views/home/index.html.erb
<br/>
<blockquote class="pull-right">
  <p>Our goal is to provide a professional tool which aids daily human resource practices in organisations all over the
world.
  </p>
  <small>Dirk Grandjean <cite title="Source Title">Founder of the project</cite></small>
</blockquote>

<br/>
<br/>
<br/>
<br/>
<br/>
<h4>You've made it!</h4>
<p>Welcome to the Blue Robin project. Whether you are just a visitor or seriously interested, feel free to navigate around the page.</p>

app/views/home/organisations.html.erb
<br/>
<h4>The added value for you as an organisation</h4>
<ol>
  <li>Entry barrier</li>
  <li>Open-source/sustainability</li>
  <li>Customisation</li>
  <li>Ownership</li>
</ol>



<h5>Entry barrier</h5>
<p>By providing a free software the Blue Robin project lowers the entry barrier for organisations to use Blue Robin. Therefore from a financial point of view Blue Robin becomes an interesting piece of art for an organisation to consider.</p>

<h5>Open-source + sustainability</h5>
<p>The software, Blue Robin, contains a MIT license which allows free usage. The aim is to share the software all across the world in order to establish world-wide acceptance. The strenght of open-source project is that fact that everyone with mad skillz can join the project and improve it. The Blue Robin project aims to reach out to those developers. For you, this means that your own IT experts can also participate in the project. A better and faster software is in best interest of all parties.</p>

<h5>Customisation</h5>
<p>Once you have downloaded the source code you will be able to adjust the software according to your own needs. In this way, the software will always fit your organisation. Once you have made your awesome changes we hope that you are willing to share those. If it is a great change, we can include it in the next release to make the software even more amazing.</p>

<h5>Ownership</h5>
<p>Since you own the software (source-code), you (as an organisation) are not dependent on the financial continuity of any organisation. Whereas before, you are dependent on the position and resources of the organisation you license the software from, you are the owner of Blue Robin. Therefore you will be able to run it within your own server and your own IT experts will be to sustain it.</p>
<p>Like stated in the open-source section. Everybody is owner of the Blue Robin project and therefore everyone with development skills can improve the software. Over time you will see that this will benefit your organisation, the project and the community. An excellent example of a succesfull open-source project is Ubuntu, which is a Linux operating system.</p>

app/views/home/project.html.erb
<br/>
<h4>Once upon a time..</h4>
<p>..there was a man with an idea and a company willingess to realise this idea.</p>
<p>The project started early 2013 as a coorporation between IceFlag and Greenpeace. Iceflag is a coorporation specialised in human resource software development whereas Greenpeace has an excellent taste for awesome software.</p>

<h5>Philosophy</h5>
<p>Current human resource (HR) systems are often expensive and needs to licensed in order to use it. Often this results in over-priced software which is mostly focused on automating HR rather than sharing some love. A company often needs only a part of you, for example, your awesome marketing skils. This is what we call a human resource. However often there is a person (with its owm personality) attached to it. This makes it hard to manage. Should we manage only the human resource? Or should we manage the person as a whole? This is often the question organisations are struggeling with. Blue Robin aims to bring in the human site in a software systems by providing a tool rather than a management system. We believe the HR manage is the expert in managing the human resource and person. Blue Robin aims to support the HR manager by providing tools which he/she can use to forefill the daily HR practises.</p>

<h5>Values</h5>
<p>The project is founded on the following values:</p>
<ul>
  <li>Knowledge-sharing</li>
  <li>Work/life balance</li>
  <li>Positive approach</li>
  <li>Passion for HR</li>
</ul>
<p>It is important to communicate those values because you will find them back in the software functions.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blue Robin Project</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'the Blue Robin project', home_index_path, :class => "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "The project", project_path %></li>
          <li><%= link_to "Organisations", organisations_path %></li>
          <li><%= link_to "Developers", developers_path %></li>
          <li><%= link_to "Contact us", contact_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<br/>
<br/>
<div class="span1">
  <br/>
</div>

<div class="span10">
  <div class="inner-body">
    <%= yield %>
  </div>
</div>

<div class="span1">
  <%= image_tag 'bird.png' %>
</div>

</body>
</html>